### ISSUE TITLE
VLC opens with random files/images

### ISSUE THREAD

**Issue by plandevida** [SecUpwN/Spotify-AdKiller#59]
On Ubuntu 15.10, Spotify (1:1.0.25.127.g58007b4c-22) and latests Spotify-AdKiller.

Several times vlc opens with an image or file, some times windowed some times in full screen. And ads are not muted.

Attached image of VLC in full screen.
![vlcsnap-2016-04-06-09h50m13s640](https://cloud.githubusercontent.com/assets/1167738/14309646/1abe54e8-fbde-11e5-8839-ab9cc49b01a0.png)
.
![sin nombre](https://cloud.githubusercontent.com/assets/1167738/14310879/87e1b334-fbe4-11e5-9d90-c6600ed1adbf.png)

**Comment by SecUpwN** [comment]
@plandevida, I don't see the relation to our script. Shouldn't you file this Issue in the [VLC repository](https://github.com/videolan/vlc)?

**Comment by plandevida** [comment]
@SecUpwN: No, I didn't. Because it's weird, this 'issue' beigns with latest Spotify AdKiller and only when I run it.

**Comment by plandevida** [comment]
I have tested _Spotify_ for a while and after _Spotify AdKiller_, in this session _VLC_ didn't open. Sure you @SecUpwN are right and we should forget this issue because is not relevant

**Comment by plandevida** [comment]
Some times still happening

**Comment by nik0lai** [comment]
[ubuntu 15.10] I have the same problem, when an ad appears on spotify a VLC window with a video, or image, reproduce. Also, the ads are not muted.
When Custom_Mode set to simple the problem with VLC disappears but the ads remains unmuted.

**Comment by nik0lai** [comment]
It seems to solve when setting CUSTOM_MODE="simple", and erasing the backup file (Spotify-AdKiller.cfg~) that appears when Spotify-AdKiller.cfg is modified.
With this the vlc problems disappears and the ads are muted.

**Comment by SecUpwN** [comment]
@nik0lai, since #54 our default mode is `continuous`. Would you please test if erasing the backup file `Spotify-AdKiller.cfg~` works with that as well? If it does, adding some removal mechanism should solve this.

**Comment by nik0lai** [comment]
@SecUpwN, I tried and the ads were muted but vlc still reproduce some random video or image.

**Comment by SecUpwN** [comment]
@nik0lai, I've just merged a few fixes created by @mikar. Please test your Issue again. Thanks.

**Comment by nik0lai** [comment]
@SecUpwN, excuse me but I'm new to github, should I reinstall following the Installation steps to get the fixes?

**Comment by SecUpwN** [comment]
@nik0lai, yes, please get a fresh copy of our repository and install it on a fresh base.

**Comment by plandevida** [comment]
I did a pull and ./install.sh, the VLC still starting...
It is enough to consider a "fresh copy" or I need to delete all files and config files?

**Comment by SecUpwN** [comment]
>It is enough to consider a "fresh copy" or I need to delete all files and config files?

@plandevida, in order to do a clean test, please remove all old files first. Thank you.

**Comment by plandevida** [comment]
I started from a fresh copy on fresh system installation (another distro ArchLinux) and still happens.

**Comment by cpappen** [comment]
Well, after installed spotify-adkiller and listened to one album on spotify, a vlc window opened with a short video with images of my work and i work on a virtualbox machine. That scared the hell out of me!

**Comment by haveatry1234** [comment]
happen the same on ubuntu 18.10 and 19.04. 
ONLY straight after a muted ad, vlc opens in full screen with the last file opened with vlc.

**Comment by keyan** [comment]
Happening for me on a fresh Ubuntu 20.04 install. Started immediately after installing/using Spotify-adkiller. VLC will open a random file a few times a day. Definitely surprising at first :)
